[build]
  command = "npm run build"
  # publish can be "." because Netlify's adapter provisions the runtime for Next.
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "18"
